export const  NotesData=[
    {
        id: 1,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#FFEB3B",
    },
    {
        id: 2,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#FFD6A5",
    },
    {
        id: 3,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#ddeeff",
    },
    {
        id: 4,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#A0E7E5",
    },
    {
        id: 5,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#E4C1F9",
    },
    {
        id: 6,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#C3F584",
    },
    {
        id: 7,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#C3F584",
    },
    {
        id: 8,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#E4C1F9",
    },
    {
        id: 9,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#A0E7E5",
    },
    {
        id: 10,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#ddeeff",
    },
    {
        id: 11,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#FFD6A5",
    },
    {
        id: 12,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#FFEB3B",
    },
    {
        id: 13,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#FFEB3B",
    },
    {
        id: 14,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#FFD6A5",
    },
    {
        id: 15,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#ddeeff",
    },
    {
        id: 16,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#A0E7E5",
    },
    {
        id: 17,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#E4C1F9",
    },
    {
        id: 18,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#C3F584",
    },
     {
        id: 19,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#C3F584",
    },
    {
        id: 20,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#E4C1F9",
    },
    {
        id: 21,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#A0E7E5",
    },
    {
        id: 22,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#ddeeff",
    },
    {
        id: 23,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#FFD6A5",
    },
    {
        id: 24,
        title: "Buy Groceries",
        date: "2025-07-09",
        content: "Milk, Bread, Eggs",
        color: "#FFEB3B",
    }

]